### ISSUE TITLE
Compiling Error with Cocoon

### ISSUE THREAD

**Issue by AndreasReitberger** [cranberrygame/cordova-plugin-ad-unityads#3]
Hi @cranberrygame 

I tried your Cordova Unity Ads plugin with Cocoon, but sadly I got a build error. Maybe it's a conflict with the Cordova upgrade of the compiler.

`FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':packageAllArmv7ReleaseClassesForMultiDex'.
  
  > java.util.zip.ZipException: duplicate entry: com/unity3d/ads/android/BuildConfig.class
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 49.368 secs
ERROR building one of the platforms: Error: cordova/platforms/android/gradlew: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: cordova/platforms/android/gradlew: Command failed with exit code 1`

Here is the post: https://forums.cocoon.io/t/unity-ads-and-c2/2026

**Comment by cranberrygame** [comment]
@AndreasReitberger 

Hi

Fixed the issue.

Thanks
Sang Ki Kwon

**Comment by AndreasReitberger** [comment]
Hi,

Thank you but the build still fails on my end.
- What went wrong:
  Execution failed for task ':shrinkArmv7ReleaseMultiDexComponents'.
  
  > java.io.IOException: Can't read [cordova/platforms/android/build/intermediates/multi-dex/armv7/release/allclasses.jar](Can't process class [com/unity3d/ads/android/cache/UnityAdsCacheThread.class] %2815360%29)
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 17.741 secs
ERROR building one of the platforms: Error: cordova/platforms/android/gradlew: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: cordova/platforms/android/gradlew: Command failed with exit code 1

**Comment by AndreasReitberger** [comment]
I just forgot to turn of "Multidex enabled" in the Android Settings. Now it's working, thank you!
